### ISSUE TITLE
Windowsでメンバーの削除が行えない

### ISSUE THREAD

**Issue by anchan828** [anchan828/deploygate-with-unity#2]
MethodのDELETEが使用できないので、うまい感じに回避策をねらなきゃいけない

**Comment by unitydev1** [comment]
hi anchan828
could You   contact me, I have a question for your google map android project for Unity
my e-mail U8-home@yandex.by
Thank you!

**Comment by anchan828** [comment]
hi,
I won't update unity-googlemapview-for-android.

**Comment by unitydev1** [comment]
ok,As far as I understand, the current version does not work?

**Comment by anchan828** [comment]
yes, the current version not work. Too many task to update :(
so you can be happy if you find other assets.

**Comment by unitydev1** [comment]
it is the api  v1, and it is necessary to transfer to the second or third version. 
If I can do it, i will upload here :)
thank you!
